version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    commit-message:
      prefix: 'fix: '
    cooldown:
      default-days: 7
    groups:
      openmeteo:
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: weekly
      time: '10:00'
    commit-message:
      prefix: 'fix: '
    cooldown:
      default-days: 7
