name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write # to create release commit (googleapis/release-please-action)
  pull-requests: write # to create release PR (googleapis/release-please-action)
  issues: write # to create labels (googleapis/release-please-action)

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          submodules: "recursive"
          lfs: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci
        if: ${{ steps.release.outputs.release_created }}

      - name: Build packages
        run: npm run build
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish to npm
        if: ${{ steps.release.outputs.release_created }}
        run: npm run publish:all
